version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-tutor-app
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://admin:.rlXI0}1mq}gf+(Gp$DGA7<%#-.7@mariadb-container/studybeam

  db:
    image: mariadb:10.5
    container_name: mariadb-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rlXI0}1mq}gf+(Gp$DGA7<%#-.7
      MYSQL_DATABASE: studybeam
      MYSQL_USER: admin
      MYSQL_PASSWORD: rlXI0}1mq}gf+(Gp$DGA7<%#-.7
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
